-- Create the Notes table for your diary entries
CREATE TABLE IF NOT EXISTS notes (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  content text,
  category text, -- e.g., 'Works', 'Ideas'
  updated_at timestamp with time zone DEFAULT now()
);

-- Create the Todos table for your task cards
CREATE TABLE IF NOT EXISTS todos (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  title text NOT NULL,
  is_completed boolean DEFAULT false,
  due_date timestamp with time zone DEFAULT now()
);

-- Create Todos Table
create table todos (
  id bigint generated by default as identity primary key,
  task_name text not null,
  is_done boolean default false,
  created_at timestamp with time zone default now()
);

-- Create Notes Table
create table notes (
  id bigint generated by default as identity primary key,
  title text,
  content text,
  color text default '#FFFFFF',
  image_url text,
  created_at timestamp with time zone default now()
);


-- Adding alter table todos for new column 
ALTER TABLE todos 
ALTER COLUMN due_date TYPE timestamp with time zone;